[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "paper-xyz"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.14.6,<3.15"
uv = ">=0.11.25,<0.12"
ruff = ">=0.15.20,<0.16"
ty = ">=0.0.55,<0.0.56"
pre-commit = ">=4.6.0,<5"
hatchling = ">=1.30.1,<2"

zellij = ">=0.44.3,<0.45"
aria2 = ">=1.37.0,<2"

nomkl = ">=1.0,<2"

pytorch = { version = ">=2.12.1,<3", build = "*cpu_generic*" }
torchvision = ">=0.27.1,<0.28"
openai = ">=2.44.0,<3"

poppler = ">=26.5.0,<27"
pandoc = ">=3.10,<4"
openpyxl = ">=3.1.5,<4"

[pypi-dependencies]
paper_xyz = { path = ".", editable = true }
ty-extensions = ">=0.1.0, <0.2"

requests = ">=2.34.2, <3"
httpx = "*"
bs4 = ">=0.0.2, <0.0.3"

# https://github.com/py-pdf/pypdf
pypdf = ">=6.14.2, <7"
# https://github.com/pymupdf/PyMuPDF
pymupdf = ">=1.28.0, <2"
# https://github.com/allenai/olmocr
olmocr = ">=0.4.27, <0.5"

# markitdown
[feature.markitdown.dependencies]
python = ">=3.14.6,<3.15"
[feature.markitdown.pypi-dependencies]
# https://github.com/microsoft/markitdown
# pixi add --pypi 'markitdown[pdf]' -f markitdown
# markitdown = { version = ">=0.0.2, <0.2", extras = ["pdf"] }
markitdown = ">=0.0.2, <0.2"

# llama
[feature.llama.dependencies]
# may needs a latest version, check `activation.env`
"llama.cpp" = ">=9802,<9803"

# mlx
[feature.mlx.system-requirements]
macos = "16.0"
[feature.mlx.target.osx-arm64.dependencies]
python = ">=3.14.6,<3.15"
mlx = ">=0.32.0,<0.33"
mlx-vlm = ">=0.6.10,<0.7"
mlx-lm = ">=0.31.3,<0.32"
torchvision = ">=0.28.0,<0.29"

# cu129
[feature.cu129.system-requirements]
cuda = "12.9"
[feature.cu129.target.linux-64.dependencies]
# CONDA_OVERRIDE_CUDA=12.9 pixi i -e cu129
# CONDA_OVERRIDE_CUDA=12.9 pixi add cuda-version=12.9 -p linux-64 -f cu129
# CONDA_OVERRIDE_CUDA=12.9 pixi add cuda-version=12.9 cuda-toolkit=12.9.1 -p linux-64 -f cu129
# pixi add "llama.cpp[build=*cuda129*]" -p linux-64 -f cu129
# pixi run -e cu129 pixi run -e llama llama-server --list-devices
cuda-version = "12.9.*"
"llama.cpp" = { version = ">=9802,<9803", build = "*cuda129*" }

# cu130
[feature.cu130.system-requirements]
cuda = "13.0"
[feature.cu130.target.linux-64.dependencies]
# CONDA_OVERRIDE_CUDA=13.0 pixi i -e cu130
# CONDA_OVERRIDE_CUDA=13.0 pixi add cuda-version=13.0 -p linux-64 -f cu130
# CONDA_OVERRIDE_CUDA=13.0 pixi add cuda-version=13.0 cuda-toolkit=13.0 -p linux-64 -f cu130
# pixi add "llama.cpp[build=*cuda130*]" -p linux-64 -f cu130
# pixi run -e cu130 pixi run -e llama llama-server --list-devices
cuda-version = "13.0.*"
"llama.cpp" = { version = ">=9802,<9803", build = "*cuda130*" }

[environments]
# default is implicit
llama = { features = ["llama"], no-default-feature = true }
mlx = { features = ["mlx"], no-default-feature = true }
markitdown = { features = ["markitdown"], no-default-feature = true }
cu129 = { features = ["cu129"], no-default-feature = true }
cu130 = { features = ["cu130"], no-default-feature = true }

[activation.env]

# https://github.com/ggml-org/llama.cpp/releases
PAPER_XYZ_PATH_0 = "${PIXI_PROJECT_ROOT}/debug_agent/llama"
PATH = "${PAPER_XYZ_PATH_0}:${PATH}"
