[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "paper-xyz"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

# default
[dependencies]
python = ">=3.14.5,<3.15"
uv = ">=0.11.19,<0.12"
ruff = ">=0.15.15,<0.16"
ty = ">=0.0.43,<0.0.44"
pre-commit = ">=4.6.0,<5"
hatchling = ">=1.30.1,<2"

zellij = ">=0.44.3,<0.45"

pytorch = ">=2.10.0,<3"
torchvision = ">=0.26.0,<0.27"
openai = ">=2.41.0,<3"

# may needs a latest version, check `activation.env`
"llama.cpp" = ">=9222,<9223"
poppler = ">=26.5.0,<27"
pandoc = ">=3.9.0.2,<4"

[pypi-dependencies]
# `src/paper_xyz`
paper_xyz = { path = ".", editable = true }
requests = ">=2.34.2, <3"
ty-extensions = ">=0.1.0, <0.2"
# https://github.com/py-pdf/pypdf
pypdf = ">=6.12.2, <7"
# https://github.com/pymupdf/PyMuPDF
pymupdf = ">=1.27.2.3, <2"
# https://github.com/pymupdf/pymupdf4llm
pymupdf4llm = ">=0.3.4, <2"
# https://github.com/allenai/olmocr
olmocr = ">=0.4.27, <0.5"
rich = ">=13.9.4, <14"

# markitdown
[feature.markitdown.dependencies]
python = ">=3.14.5,<3.15"

[feature.markitdown.pypi-dependencies]
# https://github.com/microsoft/markitdown
# pixi add --pypi 'markitdown[pdf]' -f markitdown
markitdown = { version = ">=0.0.2, <0.2", extras = ["pdf"] }

[environments]
# default is implicit
markitdown = { features = ["markitdown"], no-default-feature = true }

[activation.env]
# https://github.com/ggml-org/llama.cpp/releases
PATH = "${PIXI_PROJECT_ROOT}/debug_agent/llama:${PATH}"
# for cuda devices
# CUDA_VISIBLE_DEVICES = "0"
# CUDA_DEVICE_ORDER = "PCI_BUS_ID"
