#!/usr/bin/env python3
"""Reference CLI for surya_ocr, always OCR to markdown.

Examples:
  pixi run -e marker python agent/surya_ocr_ref.py agent/demo.pdf --output md/demo.surya.md
  pixi run -e marker python agent/surya_ocr_ref.py agent/demo.png --tmp-dir debug_agent/surya_ocr --save-images --output md/demo.surya.md
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path
from typing import Any


def run_surya(
    *,
    input_path: Path,
    tmp_dir: Path,
    save_images: bool = False,
) -> None:
    tmp_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        "surya_ocr",
        str(input_path),
        "--output_dir",
        str(tmp_dir),
    ]
    if save_images:
        cmd.append("--images")
    subprocess.run(cmd, check=True)


def find_results_json(input_path: Path, tmp_dir: Path) -> Path:
    expected = tmp_dir / input_path.stem / "results.json"
    if expected.is_file():
        return expected

    candidates = sorted(tmp_dir.rglob("results.json"))
    if not candidates:
        raise SystemExit(f"Cannot find results.json under: {tmp_dir}")
    return candidates[0]


def normalize_text(raw: str) -> str:
    text = raw.strip()
    if not text:
        return ""
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def lines_for_page(page: dict[str, Any]) -> list[str]:
    lines: list[tuple[float, float, str]] = []
    for line in page.get("text_lines", []):
        text = normalize_text(str(line.get("text") or ""))
        if not text:
            continue

        bbox = line.get("bbox") or [0.0, 0.0]
        x = float(bbox[0]) if len(bbox) >= 1 else 0.0
        y = float(bbox[1]) if len(bbox) >= 2 else 0.0
        lines.append((y, x, text))

    lines.sort(key=lambda item: (item[0], item[1]))
    return [text for _, _, text in lines]


def write_markdown(results_path: Path, output_md: Path) -> None:
    data = json.loads(results_path.read_text(encoding="utf-8"))
    output_md.parent.mkdir(parents=True, exist_ok=True)

    with output_md.open("w", encoding="utf-8") as out:
        for doc_idx, (doc_name, pages) in enumerate(data.items()):
            if doc_idx:
                out.write("\n")
            out.write(f"# OCR Output: {doc_name}\n\n")

            for page in pages:
                page_no = page.get("page", "?")
                out.write(f"## Page {page_no}\n\n")
                for text in lines_for_page(page):
                    out.write(f"{text}\n")
                out.write("\n")

    print(f"[surya_ocr] {results_path} -> {output_md}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Run surya_ocr once and export markdown from OCR results. "
            "Example input: agent/demo.png or agent/demo.pdf."
        ),
    )
    parser.add_argument(
        "input_path",
        help="Input file path, PDF or image. Example: agent/demo.png.",
    )
    parser.add_argument(
        "--output",
        "-o",
        required=True,
        help="Markdown output path.",
    )
    parser.add_argument(
        "-d",
        "--tmp-dir",
        required=True,
        help="Temporary directory used by surya_ocr for intermediate outputs.",
    )
    parser.add_argument(
        "--save-images",
        action="store_true",
        help="Save OCR bbox images generated by surya_ocr.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    input_path = Path(args.input_path)
    if not input_path.exists():
        raise SystemExit(f"Input file not found: {input_path}")

    tmp_dir = Path(args.tmp_dir)
    output_md = Path(args.output)

    run_surya(
        input_path=input_path,
        tmp_dir=tmp_dir,
        save_images=args.save_images,
    )
    results_path = find_results_json(input_path, tmp_dir)
    write_markdown(results_path, output_md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
